version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
stages:
  build:
    workDir: ~/my-project
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: ls && tree
